server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_generate?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
